### ISSUE TITLE
apt가 심하게 느립니다.

### ISSUE THREAD

**Issue by zanywhale** [KAIST-IS521/2018-Spring#100]
deb.debian.com에서 받아오는 apt 설치가 정말 심하게 느립니다.
모든 Dockerfile에 

```
RUN \
  sed -i 's/deb.debian.org/ftp.daumkakao.com/g' /etc/apt/sources.list
```

위 코드 한 줄만 넣어주시면 안될까요?

**Comment by sangkilc** [comment]
We will have to redistribute `config.json` file if we do so. We will also have to stop the evaluation server while updating the file. It will take about an hour, and we will notify here.
