### ISSUE TITLE
TEAM2의 프로그램상 문제로 검증에 문제가 있습니다.

### ISSUE THREAD

**Issue by AhnMo** [KAIST-IS521/2018-Spring#103]
script를 통해서 submit을 할 때 기존에 브렌치로 존재하는 버그를 순회하는데, 

이 과정에서 4000번 포트가 TIME_WAIT 되어서 bug4 검증 시 서버가 정상적으로 LISTEN하지 못하는 상태가 됩니다.

이는 프로그램상 SO_REUSEADDR를 주어야 해결되는 문제로 클라이언트 프로그램에서는 어떻게 할 수가 없습니다.

이와 관련된 조치가 필요하지 않나 생각됩니다.

**Comment by jchoi2022** [comment]
네, 해당 문제를 파악하고 논의중에 있습니다. 곧 경과를 알려드리겠습니다.

**Comment by hestati63** [comment]
team4도 동일한 issue가 존재하는것 같습니다.

**Comment by seongil-wi** [comment]
우선, team2와 team4에 해당 문제가 있어서 수정후 push하였습니다.
새로 적용된 config.json을 이용하여 다시 시도해 주시기 바랍니다!

감사드립니다.
