### ISSUE TITLE
submmit 관련 질문입니다

### ISSUE THREAD

**Issue by saykim0727** [KAIST-IS521/2018-Spring#115]
![image](https://user-images.githubusercontent.com/12270593/40624315-d17c716c-62e6-11e8-8209-df925db30ff8.png)

에러로 질문을 드렸었는데 용량을 매우 작게 만들어도 이슈가 생성되지 않네요.
혹시 token은 어떻게 쓰는건가요?

**Comment by seongil-wi** [comment]
Settings -> Developer settings -> Personal access tokens -> Generate new token 클릭, 항목에서 모두 체크하여 생성후 이용하시면 됩니다.
config.json에 teams repo 이름도 제대로 되 있는지 확인해 주시고, 
그럼에도 불구하고 되지 않는다고 하면, encrypted 된 파일을 issue 제출 convention에 맞춰서 수동으로 체출하시는 방법도 있습니다!

**Comment by sangkilc** [comment]
https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line/
