### ISSUE TITLE
About pull request with unverified sign.

### ISSUE THREAD

**Issue by k1rh4** [KAIST-IS521/2018-Spring#12]
I pulled request my repository with sign commit.
But, i didn't know that commit email have to same with public-key's email.  ( "TA" talked to me  )
In my defense, this is first time commit with PGP. 
And there was no comment about this problem.

I tried to fix this issue but I can't handle now about pull request.
I added email that is public-key's email, but "pull request" did not change. because commit email and public key email is different.

Could you tell me what am i suppose to do?

**Comment by soomin-kim** [comment]
편의를 위해 한국어로 답변하겠습니다!

저라면 이렇게 할 것 같습니다:
1. 일단 PR을 닫습니다.
2. local repo에서 unverified된 커밋의 author 정보를 수정합니다.([여기](http://jojoldu.tistory.com/120) 참조)
3. `git push -f` 와 같은 명령어를 이용하여 remote repo를 강제로 수정합니다.
4. 다시 PR을 합니다.

remote repo에 있는 commit을 강제로 수정했을 때 그게 PR에 반영되는지는 모르겠네요.
도움이 되셨길 바랍니다.
감사합니다.

**Comment by oxsignal** [comment]
You don't have to close your PR,  just update your commit then it will be applied to your PR automatically.

+
To prevent messing up the commit logs, you can push only last commit.

 please refer below link:
[LINK](https://stackoverflow.com/questions/5256021/send-a-pull-request-on-github-for-only-latest-commit)

**Comment by k1rh4** [comment]
Thank you guys. 

Problem solved.
