### ISSUE TITLE
Homework의 Newline Character 부분에 대해 질문 있습니다.

### ISSUE THREAD

**Issue by Hexife** [KAIST-IS521/2018-Spring#2]
0226.md 의 Git Activity (Warm-up)에서 이해가 되지 않는 부분이 있습니다.

설명 중에 다음과 같은 구절이 있습니다.
`We assume that our CSV data do not contain new lines.`

저는 보통의 CSV 파일은 Record의 구분을 위해 new line character(\n)이 사용되는 것으로 알고 있었는데, 위 문장을 평가에 사용되는 CSV 파일에는 new line character(\n)가 없다라고 이해를 하였습니다.

평가에 사용되는 CSV 파일이 일반적으로 사용되는 아래와 같은 형태와 다른지요?

```
names,mails
taekjin,hexife@kaist.ac.kr
```

감사합니다.

**Comment by sunnyeo** [comment]
저도 같은 고민을 했는데...
csv 파일이 아닌 데이터 자체 즉, name이나 email에 new line이 없다는걸 의미하시는게 아닐까요?

**Comment by sangkilc** [comment]
When I said CSV data, it means CSV fields. I clarified the description. See 4dab3d3ad19a36778757cb55ed17a18bbc545ec1
