### ISSUE TITLE
[Onion Messenger] About onion messenger specification.

### ISSUE THREAD

**Issue by hestati63** [KAIST-IS521/2018-Spring#39]
I have two questions about onion messenger.

1. Should messages relay all the clients in the network?

2. In onion routing, receiver doesn't know who is sender. In onion messenger, should receiver know sender or not?

**Comment by sangkilc** [comment]
1. Not necessarily
2. End users should know each other. For example, even though a message is coming from client A, the message is not necessarily originated from A.

You can close this issue if there is no further questions.
