### ISSUE TITLE
Character Set 관련 질문입니다.

### ISSUE THREAD

**Issue by Hexife** [KAIST-IS521/2018-Spring#4]
Homework 설명 문에는 평가 CSV파일의 Character Set에 대한 설명이 없는데, 저희가 작성하는 코드가 유니코드 문자열도 지원해야 하는지 궁금합니다.

감사합니다.

**Comment by sangkilc** [comment]
We do not (and will not) list every single case in the activity document. It is your design decision as a programmer. It is always a good practice to write your design decisions in your `README.md`. Remember, your goal is to make your program concise, i.e., you want to consider various aspects in your design, but it should be brief at the same time.
