### ISSUE TITLE
Onion messanger 과제의 GITHUB ID용도가 궁금합니다.

### ISSUE THREAD

**Issue by k1rh4** [KAIST-IS521/2018-Spring#40]
Onion messanger 과제의 GITHUB ID용도가 궁금합니다.
GITHUB ID 라는게 반드시 GITHUB의 ID 인 것인지 아니면 이름 용도(신원파악용)의 ID 인지  문의드립니다.

**Comment by sangkilc** [comment]
To obtain a PGP key from https://github.com/KAIST-IS521/2018-Spring/tree/master/IndividualKeys

**Comment by sangkilc** [comment]
Let me clarify my comment. You do *not* need to fetch PGP keys from this repo, but it is just one option. You can think of it as a name or a unique id of a client.
