### ISSUE TITLE
About `without calling libc function`.

### ISSUE THREAD

**Issue by hestati63** [KAIST-IS521/2018-Spring#53]
There is a question about virus activity.

Does `without calling libc function` mean that we also cannot call `statically compiled` libc function or does it just mean that binary should be self-contained?

**Comment by soomin-kim** [comment]
I think the intended work is not to use libc functions in any form.
Maybe @sangkilc will leave a comment to make sure of this.

Soomin Kim

**Comment by sangkilc** [comment]
Binary should be self-contained :)
