### ISSUE TITLE
Suggestion about test environment in malware activity

### ISSUE THREAD

**Issue by Hexife** [KAIST-IS521/2018-Spring#55]
안녕하세요!

Malware Activity에서 테스트하는 환경에 wget 관련 미설치 이슈가 있어 보여서 이슈로 남기게 되었습니다.

현재 Activity에는 다음과 같이 작성되어 있습니다.

Your virus should run on Debian 64-bit system. More specifically, it should just work if we run the binary on an official Debian docker container. In other words, it should run when we do:
```
$ docker run --rm -it debian # Debian official docker
### Inside docker
$ wget https://... # obtain your virus inside docker
$ ./virus # it should simply run like this.
```

Activity를 진행하기 위해 개발환경/테스트환경을 조성하던 중에 wget이 pure debian image에는 설치 되어 있지 않은 것을 확인하였습니다.

```
hexife@hexife-LAB:~/IS521/IS521_virus/testbad$ sudo docker run -it  --name virus debian
root@d6a00e8c96fe:/# wget
bash: wget: command not found
```
wget, curl, git 세개의 바이너리 모두 설치되어 있지 않아 이들 중 하나를 설치 후 virus 바이너리를 실험해야 할 것으로 생각됩니다.

감사합니다.

**Comment by sangkilc** [comment]
This is about your virus. Your virus should not assume there is a `wget` installed. Close this issue if you think this answer makes sense.

**Comment by Hexife** [comment]
추후에 평가시에도 제시된 명령어로 테스트 될것이라고 생각하여 혹시나 싶어 이슈로 말씀드리고 싶었습니다. 

개발시에는 고려하지 않아도 된다는 점은 이해 했습니다.

감사합니다.
