### ISSUE TITLE
Question about virus.c code

### ISSUE THREAD

**Issue by S-KYUCHAN** [KAIST-IS521/2018-Spring#56]
교수님이 주신 virus.c 코드안에 nftw, memcmp 와 같은 libc 함수들도 있습니다.

함께 동봉된 Makefile에서 -nostdlib 옵션을 주면 이 함수들을 사용 못하게 되는데 이 부분이 의도된 것인지 궁금합니다.

**Comment by sangkilc** [comment]
It is intended :) You should make it work without using libc functions.
