### ISSUE TITLE
Question about gcc compile flags

### ISSUE THREAD

**Issue by S-KYUCHAN** [KAIST-IS521/2018-Spring#57]
교수님께서 Makefile을 원하는대로 수정할 수 있다고 하셨는데, 꼭 들어가야 하는 flag가 있나요??

예를들면 optimize하는 옵션을 교수님이 주신 Makefile에는 -O2인데 -O0로 바꾸는것은 가능한지 궁금합니다.

감사합니다.

**Comment by sangkilc** [comment]
You can freely change options as long as the resulting binary works on a vanilla Debian docker container.
