### ISSUE TITLE
How to tell a binary is 'benign'

### ISSUE THREAD

**Issue by 2dvorak** [KAIST-IS521/2018-Spring#58]
benign의 범주에 대해서 질문드리고자 합니다.

1. 한 바이너리가 다른 파일들을 열고, 읽는 행위를 한다면 benign 하다고 할 수 있을까요?

2. 한 바이너리가 다른 파일들을 열고, 읽은 다음 내용이 변하지 않는 범위에서 쓰는 행위를 한다면 benign 하다고 할 수 있을까요?(예를 들면 0x1C가 있는 위치에 0x1C를 써서 파일의 내용은 변하지 않는 경우)

3. 한 바이너리가 다른 파일들을 열고, 읽은 다음 파일의 동작에 아무런 영향을 주지 않는 범위 내에서 쓰는 행위를 한다면 benign 하다고 할 수 있을까요?(예를 들면, #51 에서 reference로 소개하신 Virus처럼 세그먼트의 패딩에 한 바이트만 바꿔놓는다던지)

감사합니다.

**Comment by sangkilc** [comment]
None of the examples you mentioned is malicious according to the definition: https://github.com/KAIST-IS521/2018-Spring/blob/master/Activities/0423.md#benign-vs-malicious.
