### ISSUE TITLE
바이러스 관련 질문

### ISSUE THREAD

**Issue by omnibusor** [KAIST-IS521/2018-Spring#60]
./virus를 실행시켜서 /bin/ls가 감염됐다고 가정합니다. 그리고 AV가 /bin/ls를 검사(./av /bin/ls)하면, 감염된 /bin/ls는 즉시 virus를 다른 binary로 propagation해야 하나요?

**Comment by sangkilc** [comment]
It totally depends on the implementation of the virus and the AV. A good AV should not have such an assumption.
