### ISSUE TITLE
바이러스 질문드립니다.

### ISSUE THREAD

**Issue by S-KYUCHAN** [KAIST-IS521/2018-Spring#61]
> 1. 주신 코드에는 rand함수를 통해 infect rate를 20%로 주셨습니다. 그 이유는 확산되는 모습을 보기 위함인 것 같은데, 저희가 짜는 코드도 이렇게 랜덤하게 감염시켜야 하는것인가요?

> 2. ELF 파일을 감염시켰을 때 그것을 명확하게 확인할 수 있게 만들어 주어야 하는것인가요? 예를들면 print를 해서 infect 되었음을 꼭 보여야 하는 것인가요?

감사합니다

**Comment by sangkilc** [comment]
1. Not necessarily
2. Not necessarily, but infected files should be able to infect other files when they run.

Thanks!
