### ISSUE TITLE
virus 관련 질문입니다.

### ISSUE THREAD

**Issue by khsdo95** [KAIST-IS521/2018-Spring#63]
1. target binary에 대한 조건이 없다고 하셨는데,
제가 임의로 조건을 추가하는 것은 큰 감점 요인인가요?
AV에 걸리지 않기 위해 트릭을 사용하였는데, PIE가 걸린 바이너리에서는 이 방식을 적용시킬 수 없습니다.
"PIE가 걸린 바이너리라면 감염시키지 않고 그대로 두겠다" 와 같은 조건을 추가한다면 어떻게 평가되는지 궁금합니다.

2. 처음의 바이러스 바이너리 대신 한 번 propagation이 발생하여 이미 감염된 바이너리를 initial virus로 취급하는 것이 가능한 지 궁금합니다. 즉, 이렇게 virus 바이너리를 만들어내도 괜찮은 지 궁금합니다.
```
gcc virus.c -o virus
gcc test.c -o dummy
./virus
mv ./dummy ./virus
```

**Comment by sangkilc** [comment]
1. Probably no deduction. But it can affect your extra points.
2. It is your design choice. I don't see any reason why it is not okay.
