### ISSUE TITLE
virus propagation 질문

### ISSUE THREAD

**Issue by omnibusor** [KAIST-IS521/2018-Spring#64]
infected binary를 실행시키면, infected binary는 반드시 적어도 한 개 이상의 "감염되지 않은 다른 binary"를 감염시켜야 하나요?
아니면, infected binary는 상황에 따라 propagation할지 안할지 결정할 수 있나요?

**Comment by sangkilc** [comment]
It should always propagate unless there is no available binaries other than itself. Note that you can infect a binary that is already infected by other virus(es).

**Comment by sangkilc** [comment]
A virus may try to detect AVs and hide its behavior though.
