### ISSUE TITLE
Anti-Virus에 대한 질문

### ISSUE THREAD

**Issue by hansh17** [KAIST-IS521/2018-Spring#65]
1. 바이러스가 감염시키는 대상은 executable한 binary만을 대상으로 하는건지 궁금합니다.
즉, relocatable file이나 shared object file, core file은 감염의 대상이 아닌지 궁금합니다.

2. ./scanner [program path] [cmd line option(s) for the program] 
여기서 provided command line option은 제가 정의하는 것인지, 이미 주어져 있다고 가정해야하는 건지 질문 드리고 싶습니다.

**Comment by sangkilc** [comment]
1. You can infect other files too.
2. You define it.
