### ISSUE TITLE
antivirus의 작동 방식에 관한 질문입니다.

### ISSUE THREAD

**Issue by hansh17** [KAIST-IS521/2018-Spring#67]
Your goal is to implement a dynamic virus scanner that takes in a program execution as input, and outputs whether the execution is malicious or not. 

Your scanner will execute the given program with the provided command line options, and check the execution of the program.

-- 
스캐너는 주어진 프로그램을 실행한다고 되어있는데, 이미 감염된 파일을 검사하는 것인지,
혹은 스캐너를 먼저 실행한 상태에서 어떤 특정 바이너리가 바이러스에 걸리는 것을 실시간으로 탐지해야하는 것인지 궁금합니다.

**Comment by sangkilc** [comment]
Scanner takes in a program execution: this means your scanner will execute a given program.

For example, by running `./scanner /bin/ls`, your scanner will execute /bin/ls and try to see if it is infected or not.
