### ISSUE TITLE
ptrace에 관한 질문

### ISSUE THREAD

**Issue by MincheolSon** [KAIST-IS521/2018-Spring#68]
docker run --rm -it debian 으로 docker를 실행하면 ptrace를 사용할 수 없고, --cap-add=SYS_PTRACE 옵션을 설정해 주어야 ptrace를 사용할 수 있었습니다.

docker에서 ptrace를 사용할 수 있는 설정으로 만들어 주시는 건지 궁금합니다.

**Comment by sangkilc** [comment]
Yes we will. Thank you for pointing this out!
