### ISSUE TITLE
Question about submission of virus binary.

### ISSUE THREAD

**Issue by Hexife** [KAIST-IS521/2018-Spring#69]
교수님 / TA 의 공개키로 암호화 해서 Virus 바이너리를 제출하려는 중에 궁금증이 생겨 이슈로 남기게 되었습니다.

1. Encryption은 교수님 공개키, TA 공개키 둘 중 하나로 해서 올리면 되나요?

2. 둘 다 해야한다면 암호화 순서는 어떻게 되나요? 교수님 공개키-TA 공개키 순인지 TA 공개키 - 교수님 공개키 순인지요? 아니면 2개의 암호화된 파일을 생성하는지요?

늦은 시간에 죄송합니다.

감사합니다.

**Comment by Hexife** [comment]
gpg -r  옵션에 복수로 넣으면 된다는 정보를 지인으로 부터 들어서 이슈를 닫겠습니다.

감사합니다.

**Comment by sangkilc** [comment]
Correct.
