### ISSUE TITLE
About developing service

### ISSUE THREAD

**Issue by hestati63** [KAIST-IS521/2018-Spring#72]
교수님께서 메일로 `Instead, we are going to
provide you a list of applications that we chose, and each team will
have to pick one from the list. ` 라고 하셨는데,
이와 상관없이 첫번째 옵션인 `developing your own service`은 여전히 valid한 옵션인건가요?

**Comment by sangkilc** [comment]
Yes you can.

**Comment by sangkilc** [comment]
I forgot to mention, but when you develop your own, you should use C or C++. I will modify the document to make it clearer.
