### ISSUE TITLE
Choose your repository

### ISSUE THREAD

**Issue by sangkilc** [KAIST-IS521/2018-Spring#74]
Leave a comment here to confirm your choice.

**Comment by zanywhale** [comment]
Team3는 `CHAT : https://github.com/andregasser/chatsrv`을 선택하겠습니다.

**Comment by omnibusor** [comment]
Team2 : https://github.com/epleaner/Networks-TCP-Chat-Program

**Comment by hestati63** [comment]
Team1: https://github.com/LeHack/hackttp

**Comment by sangkilc** [comment]
Still waiting for Team 4 and 5.

Other teams should check the activity document. We have specified expected outcome from the preparation phase.

**Comment by eternalklaus** [comment]
Team5 :  We'll develop our own service.

**Comment by 2dvorak** [comment]
Team4 : [https://github.com/dhuertas/http](https://github.com/dhuertas/http)

**Comment by sangkilc** [comment]
Team5 is going to take https://github.com/TimothyCH/FTP-Client-Server
