### ISSUE TITLE
About additional library use

### ISSUE THREAD

**Issue by AhnMo** [KAIST-IS521/2018-Spring#76]
open-source project의 [List](https://github.com/KAIST-IS521/2018-Spring/blob/master/Activities/List.md)을 주셨는데, 해당 프로젝트에 별개의 라이브러리를 가져다 개발을 해도 상관이 없나요?

예를 들어 [TinyXML2](https://github.com/leethomason/tinyxml2/)나 [libharu](http://libharu.sourceforge.net/)와 같은 기능적인 확장을 위한 라이브러리입니다.

**Comment by sangkilc** [comment]
Yes you can!
