### ISSUE TITLE
기존 소스코드 수정

### ISSUE THREAD

**Issue by omnibusor** [KAIST-IS521/2018-Spring#78]
기존 소스코드에 문제가 많아 보여서 이를 먼저 수정한 후에 취약점을 심어도 될까요?

**Comment by omnibusor** [comment]
그러니까, 미리 패치를 해도 될까요?

**Comment by sangkilc** [comment]
You can, but you should first push the original code as it is, and then start modifying the code. That's the part of the preparation step.
