### ISSUE TITLE
Important Notice

### ISSUE THREAD

**Issue by sangkilc** [KAIST-IS521/2018-Spring#79]
We have updated the templates and scripts we provided earlier. You should not assume that our scoring system will run the `setup.sh` in the previous docker templates. Instead, we will simply run an all-in-one tool called `gitctf.py`. Please read the updated activity document to see what I mean.

At this point, the tool can only support the 1st and the 2nd phase of the CTF: preparation and injection phase. On Wed. TA session, we will release a complete version, and we will demonstrate how you can use the tool for the final phase.

If you have any issue about the tool, go to the tool's repo, and create an issue there: https://github.com/KAIST-IS521/2018s-gitctf-script.

One final note: every team should create their team's public key and upload it to https://github.com/KAIST-IS521/2018-Spring/tree/master/GroupKeys.

**Comment by zanywhale** [comment]
Is there a convention for team's public PGP key names?
Because we don't have our team name in this activity.

**Comment by sangkilc** [comment]
You can simply use `teamN` if you don't have anything better.

**Comment by sangkilc** [comment]
Actually, let's just use `teamN.pub` to make them consistent.
