### ISSUE TITLE
Can we cleanup the master branch?

### ISSUE THREAD

**Issue by hestati63** [KAIST-IS521/2018-Spring#97]
During injection phase, can we clean up the master branch(eg. remove unnessary files).

Also can we slightly modify the master branch?

**Comment by seongil-wi** [comment]
네, 가능합니다.

다만, master에서 수정된 내용이 bugN 브랜치에서 인젝트한 버그코드부분과 크게 겹치지 않도록 하는 minor한 수정이었으면 합니다.
